// <auto-generated />
namespace LearningSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-rc1-20726")]
    public sealed partial class manytomanyrelationship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(manytomanyrelationship));
        
        string IMigrationMetadata.Id
        {
            get { return "201309291056366_many-to-many-relationship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
